#!/usr/bin/perl

use warnings;
use strict;

chomp(@ARGV = <STDIN>) unless @ARGV;
for (@ARGV) {
  my $was = $_;
  s/ - /./;
  s/_-_/./;
  if ($_ ne $was) {
    if (-e $_) {
      print STDERR "Not renaming $was to $_ (file exists)!\n";
    } else {
      print "$was -> $_\n";
      rename($was, $_);
    }
  }
}
