#!/bin/bash -

if [ $# -eq 0 ]; then
  echo >&2 "Usage: $(basename $0) file ..."
  exit 1
fi

k=1
len=${##}

# check whether there are collisions
ok=1
for file; do
  n=$(printf "%0*i" $len $k)
  new="$n.$file"
  if [[ -e $new ]]; then
    echo >&2 "File $new already exists."
    ok=0
  fi
  ((++k))
done
if (( ok == 0 )); then
  exit 2
fi

k=1
for file; do
  n=$(printf "%0*i" $len $k)
  new="$n.$file"
  printf '%s -> %s\n' "$file" "$new"
  mv "$file" "$new" || echo >&2 "Can't rename $file to $new: $!"
  ((++k))
done
