#!/bin/bash -

if [ $# -eq 0 ]; then
  echo >&2 "Usage: $(basename $0) file ..."
  exit 1
fi

uuid="[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
rename "s/-$uuid\././; s/\s+\[$uuid\]\././" "$@"
